name: Daily Scraping and CSV Update

on:
  schedule:
    - cron: '0 3 * * *'  # 毎日3時に実行（UTC時間）
  push:
    branches:
      - main
  workflow_dispatch:  # 手動トリガーを有効にする設定

jobs:
  scrape_and_update_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraping Script
      run: |
        python scrape.py

    - name: Run Cleanup Script
      run: |
        python add_unique_data.py

    - name: Transfer CSV and Blog Parts to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 必ず正しいSSHキーを設定する
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 10022 -H sv5001.wpx.ne.jp >> ~/.ssh/known_hosts

        # 固定フォルダ名（例: 最初に作成した日付のフォルダ）
        FIXED_FOLDER="2024-11-04"  # 必要ならアップデートの日付に合わせて変更

        # Ensure the fixed folder exists on the server
        ssh -p 10022 kkkk777@sv5001.wpx.ne.jp "mkdir -p /home/kkkk777/public_html/blogparts/$FIXED_FOLDER"

        # Transfer CSV file
        scp -P 10022 data.csv kkkk777@sv5001.wpx.ne.jp:/home/kkkk777/public_html/blogparts/$FIXED_FOLDER/

        # Transfer Blog Parts (JS and CSS)
        scp -P 10022 blogpart.js kkkk777@sv5001.wpx.ne.jp:/home/kkkk777/public_html/blogparts/$FIXED_FOLDER/
        scp -P 10022 blogpart.css kkkk777@sv5001.wpx.ne.jp:/home/kkkk777/public_html/blogparts/$FIXED_FOLDER/
